### ISSUE TITLE
Topics not shown on users with ~100+ topics

### ISSUE THREAD

**Issue by deliriumbg** [RMcGirr83/phpBB-3.1-searchusertopics#4] opened 2015-12-13 15:33 UTC
Hi there,

There's a bug, where topics are not shown for users, who have ~100+ topics created. 
Once clicking on the "Search user topics" the following is shown:

The search found X results form (X is usually 2 or 4..).
And then: "No suitable matches were found".

Users with below 100 topics (tested on 72 and below that) have no issues displaying them.

**Comment by rmcgirr83** [comment] 2015-12-13 17:05
Can't reproduce this

![noname](https://cloud.githubusercontent.com/assets/179079/11768141/cdae5d16-a191-11e5-949f-4a01a8b6a96e.jpg)

have any other extensions installed that have to do with search.php?  search.php is a default file of the forum software all I do in this extension is to provide a link to the same file with the parameters pre-filled.

**Comment by deliriumbg** [comment] 2015-12-13 17:09
Hmm. I suppose that "bestanswer" by kinerity might be the issue (unfortunately not supported now).
I get this error where topic are displayed without issues:
[phpBB Debug] PHP Notice: in file [ROOT]/ext/kinerity/bestanswer/event/listener.php on line 187: Undefined variable: topic_array

Indeed the users that have no topics shown have some answered topics.

**Comment by rmcgirr83** [comment] 2015-12-13 17:24
And that's what you get for installing an unvalidated extension onto a live forum.  Uninstall the extension and see if that fixes your issues.

**Comment by rmcgirr83** [comment] 2015-12-13 17:33
Indeed it is very much due to that extension and nothing to do with this one so closing.

**Closed as completed by rmcgirr83** 2015-12-13 17:33 UTC
Labels: invalid
